### ISSUE TITLE
got a compile-time error when cmpile the spark-streamingsql-master

### ISSUE THREAD

**Issue by wlwgcdxc** [Intel-bigdata/spark-streamingsql#16]
Hi,I have a question when compile the spark-streamingsql-master using the command sbt under spark-streamingsql-master.
The following is the error stack:

[error] /opt/xcdong/spark-streamingsql-master/src/main/scala/org/apache/spark/sql/streaming/SchemaDStream.scala:64: not found: type CreateTableAsSelect
[error] case : InsertIntoTable | _: CreateTableAsSelect[] | _: WriteToFile =>
[error] ^
[error] /opt/xcdong/spark-streamingsql-master/src/main/scala/org/apache/spark/sql/streaming/StreamSQLContext.scala:63: type mismatch;
[error] found : org.apache.spark.sql.types.StructType
[error] required: Seq[org.apache.spark.sql.types.DataType]
[error] val rowStream = stream.transform(rdd => RDDConversions.productToRowRdd(rdd, schema))
[error] ^
[error] /opt/xcdong/spark-streamingsql-master/src/main/scala/org/apache/spark/sql/streaming/StreamSQLParser.scala:49: not enough arguments for method apply: (input: String, exceptionOnError: Boolean)Option[org.apache.spark.sql.catalyst.plans.logical.LogicalPlan] in class StreamSQLParser.
[error] Unspecified value parameter exceptionOnError.
[error] Some(apply(input))
[error] ^
[error] three errors found
error Compilation failed
[error] Total time: 6 s, completed Dec 21, 2015 4:49:07 AM

What's wrong with it? ^_^
Thanks.

**Comment by adrian-wang** [comment]
I've seen this error before because of spark version. What version of Spark are you using, and what version of StreamingSQL here?

**Comment by wlwgcdxc** [comment]
This error really is due to spark version.I've compiled the package for spark 1.4.1 used in my cluster.
Thanks.^_^

**Comment by adrian-wang** [comment]
So I'm closing this one, thanks!
